### ISSUE TITLE
Dates with strict tables

### ISSUE THREAD

**Issue by lllama** [delaneyj/toolbelt#10]
I have the following table

```sql
create table accessRequests (
	id integer primary key,
	requestedBy integer,
	mailbox integer not null,
	requestedAt text not null,
	foreign key (mailbox) references mailboxes(id),
	foreign key (requestedBy) references users(id)
) strict;
```

Note that my `requestedAt` is set as `text`, which is due to `strict` tables not supporting `datetime` as a type.

Something during `generate` as decided that `requestedAt` will be a `time.Time` in Go, so we get 

```go
m.Requestedat = toolbelt.JulianDayToTime(ps.stmt.ColumnText(3))
```
in the generated code, which throws build errors:

```
database/crud_main_access_requests.go:48:22: 
cannot use toolbelt.TimeToJulianDay(m.Requestedat) (value of type float64) as string value 
in argument to ps.stmt.BindText
```

I'm guessing this is sqlc doing something too clever but filing here in case it's not.

**Comment by lllama** [comment]
This looks to be the culprit:

https://github.com/delaneyj/toolbelt/blob/main/sqlc-gen-zombiezen/zombiezen/queries.go#L114

**Comment by delaneyj** [comment]
Interesting, is the reason you want TEXT just to make it easier to view?  It's quite a bit slower to use text vs a real. I'd like to know more about your use case @lllama

**Comment by lllama** [comment]
The use case was using `strict` tables and picking one of the available types 😅. I think I then looked at the date functions and saw one is returning text...

**Comment by delaneyj** [comment]
julain works with any date, sqlite functions return text for convenience

**Comment by delaneyj** [comment]
Gonna close until you are ready to fight me :P
