### ISSUE TITLE
Support nullable types

### ISSUE THREAD

**Issue by lllama** [delaneyj/toolbelt#11]
I have some columns in my schema where I'd like to support NULL values. Say I have a table like:

```sql
create table testTable (
	id integer primary key,
	myBool boolean
) strict;
```

The `myBool` value will be set based on a user action. Until then, the value should be `NULL`. Other sqlc generators will emit the `sql.Null...` types. e.g. https://pkg.go.dev/database/sql#NullString or there is the option to emit pointers instead (see `emit_pointers_for_null_types` in https://docs.sqlc.dev/en/latest/reference/config.html#go)

**Comment by delaneyj** [comment]
#12
