### ISSUE TITLE
Prometheus

### ISSUE THREAD

**Issue by gedw99** [delaneyj/toolbelt#2]
would be nice to add basic Prometheus and then use it from Data Star.

The metrics can then be used for autoscaling on fly.io, and sale to zero in all global regions.

I am running on fly and it's impressive how fast it runs.

**Comment by delaneyj** [comment]
Datastar is a frontend framework, not sure what you mean.  Any promtail would be tracking normal HTTP traffic of you server, not Datastar.  Please clarify

**Comment by gedw99** [comment]
Actually it's ok how it is for now. I first need to think about it more when I have more time.

Will close for now.
