### ISSUE TITLE
Nats Server configuration options

### ISSUE THREAD

**Issue by gedw99** [delaneyj/toolbelt#3]
I would like to  change the function signature that is used to start the NATS embedded Server, so that the  folder, that is used for storage, can be passed in and used. 

That function  is here:
https://github.com/delaneyj/datastar/blob/main/backends/go/site/router.go#L146

```go
ns, err := toolbelt.NewEmbeddedNATsServer(context.Background(), true)
```

Also this function is affected here:
https://github.com/delaneyj/datastar/blob/main/backends/go/site/routes_home.go#L25
```go
func setupHome(router chi.Router, store sessions.Store, ns *toolbelt.EmbeddedNATsServer) error 
```

Also I would like to support using a NATS Cluster. I imagine that  a separate Function call, is best for this ?

Then, in the Datastart repo, we can expose these changes so that everyone can have the flexibility to use it for their deployment options. In order to do that, we will probably need a PR in DataStar so that these options can be configured with environment variables  also ?

**Comment by delaneyj** [comment]
You closed this without a PR @gedw99

**Comment by delaneyj** [comment]
You didn't say what you wanted the new signature to be so I was on standby.

**Comment by delaneyj** [comment]
Datastar works either way.  It's usage is completely orthogonal to this unless I'm missing something

**Comment by delaneyj** [comment]
Setting up NATS to be used with Datastar means just using a `*nats.Conn` and doesn't need anything special.  Embedded is the special case and reason for its inclusion here.
